/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omochimetaru_ironcake_NativeTask */

#ifndef _Included_com_omochimetaru_ironcake_NativeTask
#define _Included_com_omochimetaru_ironcake_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omochimetaru_ironcake_NativeTask
 * Method:    nativeStaticInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omochimetaru_ironcake_NativeTask_nativeStaticInit
  (JNIEnv *, jclass);

/*
 * Class:     com_omochimetaru_ironcake_NativeTask
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omochimetaru_ironcake_NativeTask_run
  (JNIEnv *, jobject);

/*
 * Class:     com_omochimetaru_ironcake_NativeTask
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omochimetaru_ironcake_NativeTask_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
